version: "3.8"

services:
  checklist-ui:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.checkky.com
      - NEXT_PUBLIC_API_KEY=checkkysignupkey
    restart: unless-stopped
